#pragma once

#include "node.hpp"

#include "visitor.hpp"
#include "program.hpp"
#include "main_func.hpp"

#include "expression.hpp"
#include "expression_list.hpp"
#include "add.hpp"
#include "and.hpp"
#include "bool.hpp"
#include "div.hpp"
#include "greater_equal.hpp"
#include "greater.hpp"
#include "identifier.hpp"
#include "integer.hpp"
#include "less_equal.hpp"
#include "less.hpp"
#include "mul.hpp"
#include "not.hpp"
#include "or.hpp"
#include "sub.hpp"
#include "mod.hpp"
#include "equal.hpp"
#include "function_call.hpp"

#include "declaration.hpp"
#include "declaration_list.hpp"
#include "var_decl.hpp"
#include "func_decl.hpp"
#include "formal_arg.hpp"
#include "formal_arg_list.hpp"

#include "statement.hpp"
#include "statement_list.hpp"
#include "assignment.hpp"
#include "if.hpp"
#include "print.hpp"
#include "var_decl_stmt.hpp"
#include "function_call_stmt.hpp"
#include "while.hpp"
#include "if_else.hpp"

#include "type.hpp"
#include "basic_type.hpp"

#include "lvalue.hpp"
#include "reference.hpp"

#include "object.hpp"
#include "type_info.hpp"